spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/bi
    username: root
    password: lhshiwode
  redis:
    # Redis服务器连接端口
    host: 47.113.186.223
    # Redis数据库索引（默认为0）
    database: 1
    port: 6379
    # 连接超时时间
    timeout: 5s
    password:
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
  rabbitmq:
    host: 47.113.186.223
    port: 5672
    username: guest
    password: guest
    virtual-host: /
#  data:
#    mongodb:
#      host: 47.113.186.223
#      port: 27017
#      database: admin
#      username: root
#      password: 123458
    data:
      mongodb:
        uri: mongodb://47.113.186.223:27017/testdb
        username: root
        password: 123456
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印sql